PEPEW_DECIMALS = 8
PEPEW_P2PKH_VERSION = 0x37
PEPEW_ADDRESS_PREFIX = "P"

# Backward-compatible alias used by earlier Phase 0/1 code.
PEPEW_DEFAULT_ADDRESS_PREFIX = PEPEW_ADDRESS_PREFIX

P2PKH_SCRIPT_PREFIX = bytes.fromhex("76a914")
P2PKH_SCRIPT_SUFFIX = bytes.fromhex("88ac")
